<?php
/**
 * Chile provinces
 *
 * @author   Hoshomoh
 * @version  1.0.1
 */

$states ['CL' ] =
  [
    'AIAI' => __( 'Aisén', 'woocommerce' ),
	'MAAC' => __( 'Antártica Chilena', 'woocommerce' ),
	'ANAN' => __( 'Antofagasta', 'woocommerce' ),
	'BIAU' => __( 'Arauco', 'woocommerce' ),
	'APAR' => __( 'Arica', 'woocommerce' ),
	'BIBI' => __( 'Biobío', 'woocommerce' ),
	'LICA' => __( 'Cachapoal', 'woocommerce' ),
	'AICP' => __( 'Capitán Prat', 'woocommerce' ),
	'LICC' => __( 'Cardenal Caro', 'woocommerce' ),
	'MLCQ' => __( 'Cauquenes', 'woocommerce' ),
	'ARCT' => __( 'Cautín', 'woocommerce' ),
	'RMCB' => __( 'Chacabuco', 'woocommerce' ),
	'ATCR' => __( 'Chañaral', 'woocommerce' ),
	'LGCE' => __( 'Chiloé', 'woocommerce' ),
	'COCH' => __( 'Choapa', 'woocommerce' ),
	'AICI' => __( 'Coihaique', 'woocommerce' ),
	'LICL' => __( 'Colchagua', 'woocommerce' ),
	'BICN' => __( 'Concepción', 'woocommerce' ),
	'ATCO' => __( 'Copiapó', 'woocommerce' ),
	'RMCD' => __( 'Cordillera', 'woocommerce' ),
	'MLCU' => __( 'Curicó', 'woocommerce' ),
	'ANEL' => __( 'El Loa', 'woocommerce' ),
	'COEQ' => __( 'Elqui', 'woocommerce' ),
	'AIGC' => __( 'General Carrera', 'woocommerce' ),
	'ATHU' => __( 'Huasco', 'woocommerce' ),
	'TPIE' => __( 'Iquique', 'woocommerce' ),
	'VSIP' => __( 'Isla de Pascua', 'woocommerce' ),
	'COLM' => __( 'Limarí', 'woocommerce' ),
	'MLLN' => __( 'Linares', 'woocommerce' ),
	'LGLL' => __( 'Llanquihue', 'woocommerce' ),
	'VSLA' => __( 'Los Andes', 'woocommerce' ),
	'MAMG' => __( 'Magallanes', 'woocommerce' ),
	'RMMI' => __( 'Maipo', 'woocommerce' ),
	'ARML' => __( 'Malleco', 'woocommerce' ),
	'VSMM' => __( 'Marga Marga', 'woocommerce' ), 
	'RMME' => __( 'Melipilla', 'woocommerce' ),
	'BINU' => __( 'Ñuble', 'woocommerce' ),
	'LGOS' => __( 'Osorno', 'woocommerce' ),
	'LGPL' => __( 'Palena', 'woocommerce' ),
	'APPR' => __( 'Parinacota', 'woocommerce' ), 
	'VSPE' => __( 'Petorca', 'woocommerce' ),
	'VSQT' => __( 'Quillota', 'woocommerce' ),
	'LRRA' => __( 'Ranco', 'woocommerce' ),
	'VSSA' => __( 'San Antonio', 'woocommerce' ),
	'VSSF' => __( 'San Felipe de Aconcagua', 'woocommerce' ),
	'RMSG' => __( 'Santiago', 'woocommerce' ),
	'RMTG' => __( 'Talagante', 'woocommerce' ), 
	'MLTC' => __( 'Talca', 'woocommerce' ),
	'TPTM' => __( 'Tamarugal', 'woocommerce' ),
	'MATI' => __( 'Tierra del Fuego', 'woocommerce' ),
	'ANTO' => __( 'Tocopilla', 'woocommerce' ),
	'MAUE' => __( 'Última Esperanza', 'woocommerce' ),
	'LRVD' => __( 'Valdivia', 'woocommerce' ),
	'VSVS' => __( 'Valparaíso', 'woocommerce' )
  ];
